[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
    command = "npm run build:ssr && npm run copy:files"
    commandOrigin = "config"
    publish = "/opt/build/repo/dist/angular-universal/browser"
    publishOrigin = "ui"
    functions = "netlify/functions/"

[functions]
    included_files = ["dist/**"]