[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
    command = "npm run build:ssr && ng run copy:files"
    functions = "netlify/functions/"

[functions]
    included_files = ["dist/**"]